### ISSUE TITLE
Error 502 BAD GATEWAY

### ISSUE THREAD

**Issue by devins-07** [pelaajahacks/zefoyBot#1]
hi when i run the exe it and it opens zefoy.com it says 502 bad gateway but when i go to zefoy.com on my iphone 11 pro it works fine. any recommendation? thanks, Devin

**Comment by pelaajahacks** [comment]
Do you have a vpn/proxy open? Zefoy sometimes gives 502 if you have a vpn.

**Comment by pelaajahacks** [comment]
Turner has a bypass discord: https://discord.gg/H8TamXS667
